// lib/game/skins/skin_themes.dart
import 'package:flutter/material.dart';

class AnimalTheme {
  final String name;
  final String emoji;
  final Color primaryColor;
  final Color secondaryColor;
  final Color accentColor;
  final String headType;
  final double speedBonus;
  final double healthBonus;
  final int damageBonus;

  const AnimalTheme({
    required this.name,
    required this.emoji,
    required this.primaryColor,
    required this.secondaryColor,
    required this.accentColor,
    required this.headType,
    required this.speedBonus,
    required this.healthBonus,
    required this.damageBonus,
  });
}

class SkinThemes {
  static const List<AnimalTheme> animals = [
    // 🟢 COMUM (poder 1-50) - 25 skins
    AnimalTheme(
        name: 'Formiga',
        emoji: '🐜',
        primaryColor: Color(0xFF5D4037),
        secondaryColor: Color(0xFF3E2723),
        accentColor: Color(0xFF8D6E63),
        headType: 'ant',
        speedBonus: 0.8,
        healthBonus: 0.5,
        damageBonus: 1),
    AnimalTheme(
        name: 'Besouro',
        emoji: '🪲',
        primaryColor: Color(0xFF2E7D32),
        secondaryColor: Color(0xFF1B5E20),
        accentColor: Color(0xFF4CAF50),
        headType: 'beetle',
        speedBonus: 0.9,
        healthBonus: 0.6,
        damageBonus: 1),
    AnimalTheme(
        name: 'Joaninha',
        emoji: '🐞',
        primaryColor: Color(0xFFC62828),
        secondaryColor: Color(0xFFB71C1C),
        accentColor: Color(0xFFEF5350),
        headType: 'ladybug',
        speedBonus: 0.7,
        healthBonus: 0.5,
        damageBonus: 1),
    AnimalTheme(
        name: 'Abelha',
        emoji: '🐝',
        primaryColor: Color(0xFFFFB300),
        secondaryColor: Color(0xFFF57C00),
        accentColor: Color(0xFFFFD54F),
        headType: 'bee',
        speedBonus: 1.2,
        healthBonus: 0.5,
        damageBonus: 2),
    AnimalTheme(
        name: 'Borboleta',
        emoji: '🦋',
        primaryColor: Color(0xFF7B1FA2),
        secondaryColor: Color(0xFF4A148C),
        accentColor: Color(0xFFBA68C8),
        headType: 'butterfly',
        speedBonus: 1.3,
        healthBonus: 0.4,
        damageBonus: 1),
    AnimalTheme(
        name: 'Gato',
        emoji: '🐱',
        primaryColor: Color(0xFFFFB74D),
        secondaryColor: Color(0xFFF57C00),
        accentColor: Color(0xFFFFE0B2),
        headType: 'cat',
        speedBonus: 1.2,
        healthBonus: 0.8,
        damageBonus: 3),
    AnimalTheme(
        name: 'Cachorro',
        emoji: '🐶',
        primaryColor: Color(0xFFBCAAA4),
        secondaryColor: Color(0xFF8D6E63),
        accentColor: Color(0xFFD7CCC8),
        headType: 'dog',
        speedBonus: 1.1,
        healthBonus: 0.9,
        damageBonus: 3),
    AnimalTheme(
        name: 'Raposa',
        emoji: '🦊',
        primaryColor: Color(0xFFFF8A65),
        secondaryColor: Color(0xFFBF360C),
        accentColor: Color(0xFFFFAB91),
        headType: 'fox',
        speedBonus: 1.3,
        healthBonus: 0.8,
        damageBonus: 4),
    AnimalTheme(
        name: 'Coelho',
        emoji: '🐰',
        primaryColor: Color(0xFFEF9A9A),
        secondaryColor: Color(0xFFC62828),
        accentColor: Color(0xFFFFCDD2),
        headType: 'rabbit',
        speedBonus: 1.3,
        healthBonus: 0.6,
        damageBonus: 2),
    AnimalTheme(
        name: 'Esquilo',
        emoji: '🐿️',
        primaryColor: Color(0xFF8D6E63),
        secondaryColor: Color(0xFF5D4037),
        accentColor: Color(0xFFBCAAA4),
        headType: 'squirrel',
        speedBonus: 1.2,
        healthBonus: 0.7,
        damageBonus: 2),

    // 🔵 INCOMUM (poder 51-100) - 10 skins
    AnimalTheme(
        name: 'Lobo',
        emoji: '🐺',
        primaryColor: Color(0xFF607D8B),
        secondaryColor: Color(0xFF37474F),
        accentColor: Color(0xFF90A4AE),
        headType: 'wolf',
        speedBonus: 1.3,
        healthBonus: 1.0,
        damageBonus: 5),
    AnimalTheme(
        name: 'Tigre',
        emoji: '🐯',
        primaryColor: Color(0xFFFFB74D),
        secondaryColor: Color(0xFFF57C00),
        accentColor: Color(0xFFFFE0B2),
        headType: 'tiger',
        speedBonus: 1.4,
        healthBonus: 1.1,
        damageBonus: 6),
    AnimalTheme(
        name: 'Leão',
        emoji: '🦁',
        primaryColor: Color(0xFFFFB74D),
        secondaryColor: Color(0xFFF57C00),
        accentColor: Color(0xFFFFE0B2),
        headType: 'lion',
        speedBonus: 1.3,
        healthBonus: 1.2,
        damageBonus: 7),
    AnimalTheme(
        name: 'Urso',
        emoji: '🐻',
        primaryColor: Color(0xFF8D6E63),
        secondaryColor: Color(0xFF5D4037),
        accentColor: Color(0xFFBCAAA4),
        headType: 'bear',
        speedBonus: 1.1,
        healthBonus: 1.4,
        damageBonus: 7),
    AnimalTheme(
        name: 'Elefante',
        emoji: '🐘',
        primaryColor: Color(0xFF9E9E9E),
        secondaryColor: Color(0xFF616161),
        accentColor: Color(0xFFE0E0E0),
        headType: 'elephant',
        speedBonus: 0.7,
        healthBonus: 1.7,
        damageBonus: 8),
    AnimalTheme(
        name: 'Águia',
        emoji: '🦅',
        primaryColor: Color(0xFF795548),
        secondaryColor: Color(0xFF4E342E),
        accentColor: Color(0xFFBCAAA4),
        headType: 'eagle',
        speedBonus: 1.5,
        healthBonus: 1.2,
        damageBonus: 9),
    AnimalTheme(
        name: 'Dragão',
        emoji: '🐉',
        primaryColor: Color(0xFFD32F2F),
        secondaryColor: Color(0xFFB71C1C),
        accentColor: Color(0xFFEF5350),
        headType: 'dragon',
        speedBonus: 1.4,
        healthBonus: 1.4,
        damageBonus: 10),
    AnimalTheme(
        name: 'Fênix',
        emoji: '🔥',
        primaryColor: Color(0xFFFF6B00),
        secondaryColor: Color(0xFFE65100),
        accentColor: Color(0xFFFF9800),
        headType: 'phoenix',
        speedBonus: 1.5,
        healthBonus: 1.5,
        damageBonus: 10),
    AnimalTheme(
        name: 'Hidra',
        emoji: '🐉',
        primaryColor: Color(0xFF2E7D32),
        secondaryColor: Color(0xFF1B5E20),
        accentColor: Color(0xFF4CAF50),
        headType: 'hydra',
        speedBonus: 1.3,
        healthBonus: 1.6,
        damageBonus: 12),
    AnimalTheme(
        name: 'Jörmungandr',
        emoji: '🐍',
        primaryColor: Color(0xFF009688),
        secondaryColor: Color(0xFF004D40),
        accentColor: Color(0xFF4DB6AC),
        headType: 'jormungandr',
        speedBonus: 1.5,
        healthBonus: 1.6,
        damageBonus: 13),

    // 🟣 RARO (poder 101-150) - 10 skins
    AnimalTheme(
        name: 'Nidhogg',
        emoji: '🐉',
        primaryColor: Color(0xFF424242),
        secondaryColor: Color(0xFF212121),
        accentColor: Color(0xFF757575),
        headType: 'nidhogg',
        speedBonus: 1.4,
        healthBonus: 1.6,
        damageBonus: 13),
    AnimalTheme(
        name: 'Apophis',
        emoji: '🐍',
        primaryColor: Color(0xFFD32F2F),
        secondaryColor: Color(0xFFB71C1C),
        accentColor: Color(0xFFEF5350),
        headType: 'apophis',
        speedBonus: 1.6,
        healthBonus: 1.5,
        damageBonus: 14),
    AnimalTheme(
        name: 'Quetzalcoatl',
        emoji: '🐉',
        primaryColor: Color(0xFF00BCD4),
        secondaryColor: Color(0xFF006064),
        accentColor: Color(0xFF4DD0E1),
        headType: 'quetzalcoatl',
        speedBonus: 1.6,
        healthBonus: 1.5,
        damageBonus: 14),
    AnimalTheme(
        name: 'Ouroboros',
        emoji: '🔄',
        primaryColor: Color(0xFF7C4DFF),
        secondaryColor: Color(0xFF3D00B0),
        accentColor: Color(0xFFB47CFF),
        headType: 'ouroboros',
        speedBonus: 1.5,
        healthBonus: 1.6,
        damageBonus: 15),
    AnimalTheme(
        name: 'Tiamat',
        emoji: '🐉',
        primaryColor: Color(0xFF0288D1),
        secondaryColor: Color(0xFF01579B),
        accentColor: Color(0xFF4FC3F7),
        headType: 'tiamat',
        speedBonus: 1.5,
        healthBonus: 1.7,
        damageBonus: 14),
    AnimalTheme(
        name: 'Fafnir',
        emoji: '🐉',
        primaryColor: Color(0xFFFFB300),
        secondaryColor: Color(0xFFF57C00),
        accentColor: Color(0xFFFFD54F),
        headType: 'fafnir',
        speedBonus: 1.4,
        healthBonus: 1.7,
        damageBonus: 15),
    AnimalTheme(
        name: 'Shenlong',
        emoji: '🐉',
        primaryColor: Color(0xFF4CAF50),
        secondaryColor: Color(0xFF2E7D32),
        accentColor: Color(0xFF81C784),
        headType: 'shenlong',
        speedBonus: 1.6,
        healthBonus: 1.6,
        damageBonus: 15),
    AnimalTheme(
        name: 'Leviatã',
        emoji: '🐋',
        primaryColor: Color(0xFF01579B),
        secondaryColor: Color(0xFF002171),
        accentColor: Color(0xFF0288D1),
        headType: 'leviathan',
        speedBonus: 1.3,
        healthBonus: 1.5,
        damageBonus: 11),
    AnimalTheme(
        name: 'Behemoth',
        emoji: '🦣',
        primaryColor: Color(0xFF4E342E),
        secondaryColor: Color(0xFF2E1E1A),
        accentColor: Color(0xFF795548),
        headType: 'behemoth',
        speedBonus: 1.0,
        healthBonus: 1.8,
        damageBonus: 11),
    AnimalTheme(
        name: 'Grifo',
        emoji: '🦁',
        primaryColor: Color(0xFFFFD54F),
        secondaryColor: Color(0xFFFFB300),
        accentColor: Color(0xFFFFE082),
        headType: 'griffin',
        speedBonus: 1.5,
        healthBonus: 1.4,
        damageBonus: 10),

    // 🟠 ÉPICO (poder 151-200) - 10 skins
    AnimalTheme(
        name: 'Quimera',
        emoji: '🦁',
        primaryColor: Color(0xFFC2185B),
        secondaryColor: Color(0xFF880E4F),
        accentColor: Color(0xFFF06292),
        headType: 'chimera',
        speedBonus: 1.4,
        healthBonus: 1.5,
        damageBonus: 11),
    AnimalTheme(
        name: 'Kraken',
        emoji: '🐙',
        primaryColor: Color(0xFF4A148C),
        secondaryColor: Color(0xFF2E0854),
        accentColor: Color(0xFF7B1FA2),
        headType: 'kraken',
        speedBonus: 1.2,
        healthBonus: 1.6,
        damageBonus: 10),
    AnimalTheme(
        name: 'Fênix Negra',
        emoji: '🔥',
        primaryColor: Color(0xFF6A1B9A),
        secondaryColor: Color(0xFF4A0072),
        accentColor: Color(0xFF9C4DCC),
        headType: 'phoenix',
        speedBonus: 1.6,
        healthBonus: 1.4,
        damageBonus: 12),
    AnimalTheme(
        name: 'Dragão Celeste',
        emoji: '🐉',
        primaryColor: Color(0xFF0288D1),
        secondaryColor: Color(0xFF01579B),
        accentColor: Color(0xFF81D4FA),
        headType: 'dragon',
        speedBonus: 1.5,
        healthBonus: 1.5,
        damageBonus: 13),
    AnimalTheme(
        name: 'Hidra Negra',
        emoji: '🐉',
        primaryColor: Color(0xFF1B5E20),
        secondaryColor: Color(0xFF0A2F0A),
        accentColor: Color(0xFF4CAF50),
        headType: 'hydra',
        speedBonus: 1.4,
        healthBonus: 1.7,
        damageBonus: 14),
    AnimalTheme(
        name: 'Jörmungandr Primordial',
        emoji: '🐍',
        primaryColor: Color(0xFF004D40),
        secondaryColor: Color(0xFF00251A),
        accentColor: Color(0xFF009688),
        headType: 'jormungandr',
        speedBonus: 1.6,
        healthBonus: 1.6,
        damageBonus: 15),
    AnimalTheme(
        name: 'Nidhogg Ancestral',
        emoji: '🐉',
        primaryColor: Color(0xFF212121),
        secondaryColor: Color(0xFF000000),
        accentColor: Color(0xFF757575),
        headType: 'nidhogg',
        speedBonus: 1.5,
        healthBonus: 1.7,
        damageBonus: 15),
    AnimalTheme(
        name: 'Apophis Divino',
        emoji: '🐍',
        primaryColor: Color(0xFFB71C1C),
        secondaryColor: Color(0xFF7F0000),
        accentColor: Color(0xFFEF5350),
        headType: 'apophis',
        speedBonus: 1.7,
        healthBonus: 1.5,
        damageBonus: 16),
    AnimalTheme(
        name: 'Quetzalcoatl Supremo',
        emoji: '🐉',
        primaryColor: Color(0xFF006064),
        secondaryColor: Color(0xFF00363A),
        accentColor: Color(0xFF4DD0E1),
        headType: 'quetzalcoatl',
        speedBonus: 1.7,
        healthBonus: 1.6,
        damageBonus: 16),
    AnimalTheme(
        name: 'Ouroboros Eterno',
        emoji: '🔄',
        primaryColor: Color(0xFF3D00B0),
        secondaryColor: Color(0xFF1A0033),
        accentColor: Color(0xFFB47CFF),
        headType: 'ouroboros',
        speedBonus: 1.6,
        healthBonus: 1.7,
        damageBonus: 17),

    // 🟡 LENDÁRIO (poder 201-240) - 8 skins
    AnimalTheme(
        name: 'Tiamat Mítica',
        emoji: '🐉',
        primaryColor: Color(0xFF01579B),
        secondaryColor: Color(0xFF002984),
        accentColor: Color(0xFF4FC3F7),
        headType: 'tiamat',
        speedBonus: 1.6,
        healthBonus: 1.8,
        damageBonus: 16),
    AnimalTheme(
        name: 'Fafnir Dourado',
        emoji: '🐉',
        primaryColor: Color(0xFFFF6F00),
        secondaryColor: Color(0xFFC43D00),
        accentColor: Color(0xFFFFD54F),
        headType: 'fafnir',
        speedBonus: 1.5,
        healthBonus: 1.8,
        damageBonus: 17),
    AnimalTheme(
        name: 'Shenlong Celestial',
        emoji: '🐉',
        primaryColor: Color(0xFF2E7D32),
        secondaryColor: Color(0xFF004D40),
        accentColor: Color(0xFF81C784),
        headType: 'shenlong',
        speedBonus: 1.7,
        healthBonus: 1.7,
        damageBonus: 17),
    AnimalTheme(
        name: 'Leviatã Profundo',
        emoji: '🐋',
        primaryColor: Color(0xFF002171),
        secondaryColor: Color(0xFF000051),
        accentColor: Color(0xFF0288D1),
        headType: 'leviathan',
        speedBonus: 1.4,
        healthBonus: 1.9,
        damageBonus: 16),
    AnimalTheme(
        name: 'Behemoth Terrestre',
        emoji: '🦣',
        primaryColor: Color(0xFF2E1E1A),
        secondaryColor: Color(0xFF140C0A),
        accentColor: Color(0xFF795548),
        headType: 'behemoth',
        speedBonus: 1.2,
        healthBonus: 2.0,
        damageBonus: 18),
    AnimalTheme(
        name: 'Grifo Real',
        emoji: '🦁',
        primaryColor: Color(0xFFFFB300),
        secondaryColor: Color(0xFFFF6F00),
        accentColor: Color(0xFFFFE082),
        headType: 'griffin',
        speedBonus: 1.7,
        healthBonus: 1.6,
        damageBonus: 16),
    AnimalTheme(
        name: 'Quimera Infernal',
        emoji: '🦁',
        primaryColor: Color(0xFF880E4F),
        secondaryColor: Color(0xFF4A0072),
        accentColor: Color(0xFFF06292),
        headType: 'chimera',
        speedBonus: 1.6,
        healthBonus: 1.7,
        damageBonus: 18),
    AnimalTheme(
        name: 'Kraken Abissal',
        emoji: '🐙',
        primaryColor: Color(0xFF2E0854),
        secondaryColor: Color(0xFF1A0033),
        accentColor: Color(0xFF7B1FA2),
        headType: 'kraken',
        speedBonus: 1.5,
        healthBonus: 1.8,
        damageBonus: 17),

    // 🌈 MÍTICO (poder 241-250) - 10 skins com cores do arco-íris
    AnimalTheme(
        name: 'Arco-Íris',
        emoji: '🌈',
        primaryColor: Color(0xFFFF0000),
        secondaryColor: Color(0xFFFF7F00),
        accentColor: Color(0xFFFFFF00),
        headType: 'rainbow',
        speedBonus: 2.0,
        healthBonus: 2.0,
        damageBonus: 20),
    AnimalTheme(
        name: 'Cósmica',
        emoji: '✨',
        primaryColor: Color(0xFFAA00FF),
        secondaryColor: Color(0xFF6200EA),
        accentColor: Color(0xFFE040FB),
        headType: 'rainbow',
        speedBonus: 2.1,
        healthBonus: 2.0,
        damageBonus: 21),
    AnimalTheme(
        name: 'Infinito',
        emoji: '♾️',
        primaryColor: Color(0xFF00BCD4),
        secondaryColor: Color(0xFF0097A7),
        accentColor: Color(0xFF80DEEA),
        headType: 'rainbow',
        speedBonus: 2.0,
        healthBonus: 2.1,
        damageBonus: 21),
    AnimalTheme(
        name: 'Eternidade',
        emoji: '⏳',
        primaryColor: Color(0xFFFFD700),
        secondaryColor: Color(0xFFFFA500),
        accentColor: Color(0xFFFFE55C),
        headType: 'rainbow',
        speedBonus: 2.2,
        healthBonus: 2.0,
        damageBonus: 22),
    AnimalTheme(
        name: 'Void',
        emoji: '🌌',
        primaryColor: Color(0xFF1A237E),
        secondaryColor: Color(0xFF0D004B),
        accentColor: Color(0xFF536DFE),
        headType: 'rainbow',
        speedBonus: 2.0,
        healthBonus: 2.2,
        damageBonus: 22),
    AnimalTheme(
        name: 'Primordial',
        emoji: '🌋',
        primaryColor: Color(0xFFFF6E40),
        secondaryColor: Color(0xFFD32F2F),
        accentColor: Color(0xFFFF8A65),
        headType: 'rainbow',
        speedBonus: 2.1,
        healthBonus: 2.1,
        damageBonus: 23),
    AnimalTheme(
        name: 'Abissal',
        emoji: '🌊',
        primaryColor: Color(0xFF006064),
        secondaryColor: Color(0xFF004D40),
        accentColor: Color(0xFF4DB6AC),
        headType: 'rainbow',
        speedBonus: 2.0,
        healthBonus: 2.3,
        damageBonus: 23),
    AnimalTheme(
        name: 'Estelar',
        emoji: '⭐',
        primaryColor: Color(0xFFFFD700),
        secondaryColor: Color(0xFFFFB300),
        accentColor: Color(0xFFFFECB3),
        headType: 'rainbow',
        speedBonus: 2.3,
        healthBonus: 2.0,
        damageBonus: 24),
    AnimalTheme(
        name: 'Nebulosa',
        emoji: '🌌',
        primaryColor: Color(0xFF7B1FA2),
        secondaryColor: Color(0xFF4A0072),
        accentColor: Color(0xFFBA68C8),
        headType: 'rainbow',
        speedBonus: 2.2,
        healthBonus: 2.2,
        damageBonus: 24),
    AnimalTheme(
        name: 'Absoluto',
        emoji: '👑',
        primaryColor: Color(0xFFFF1744),
        secondaryColor: Color(0xFFD50000),
        accentColor: Color(0xFFFF5252),
        headType: 'rainbow',
        speedBonus: 2.5,
        healthBonus: 2.5,
        damageBonus: 30),
  ];

  static AnimalTheme getThemeByPower(int power) {
    // Garantir que power está dentro do intervalo (1-250)
    final safePower = power.clamp(1, 250);

    // Mapeia power para índice na lista de animais
    // Total de animais: 53
    final int index;
    if (safePower <= 50) {
      // 1-50: primeiros 10 animais (repetindo)
      index = (safePower - 1) % 10;
    } else if (safePower <= 100) {
      // 51-100: próximos 10 animais (índices 10-19)
      index = 10 + ((safePower - 51) % 10);
    } else if (safePower <= 150) {
      // 101-150: próximos 10 animais (índices 20-29)
      index = 20 + ((safePower - 101) % 10);
    } else if (safePower <= 200) {
      // 151-200: próximos 10 animais (índices 30-39)
      index = 30 + ((safePower - 151) % 10);
    } else if (safePower <= 240) {
      // 201-240: próximos 8 animais (índices 40-47)
      index = 40 + ((safePower - 201) % 8);
    } else {
      // 241-250: últimos 10 animais (índices 48-57)
      index = 48 + ((safePower - 241) % 10);
    }

    // Garantir que o índice está dentro do range
    final safeIndex = index.clamp(0, animals.length - 1);
    return animals[safeIndex];
  }
}
